## Vector
A tuple of one or more values called scalars. It is common to represent the target variable as a vector with "y".

### Defining a Vector
A vector can be represented as a Numpy array created by a list of numbers.

### Vector Arithmetic
- **Addition**
    - c = a + b
    - two vectors of equal length can be added to create a new third vector
    - the new vector has the same length of the other two vectors
        - a + b = (a1+b1, a2+b2, a3+b3)
    - you can add vectors by adding Numpy arrays

- **Subtraction**
    - c = a - b
    - one vector of equal length can be subtracted from another
    - the new vector has the same length of the other two vectors
        - a - b = (a1-b1, a2-b2, a3-b3)
    - Numpy arrays can be subtracted in python

- **Multiplication**
    - c = a * b
    - one vector of equal length can be multiplied with another
    - the new vector has the same length of the other two vectors
        - a * b = (a1b1, a2b2, a3b3)
    - Numpy arrays can be multiplied in python
 
- **Division**
    - c = a / b
    - two vectors of equal length can be divided
    - the new vector has the same length of the other two vectors
        - a / b = (a1/b1, a2/b2, a3/b3)
    - Numpy arrays can be multiplied in python
    
- **Dot Product**
    - The sum of the multiplied elements of two vectors of the same length
    - c = a . b
    - a . b = (a1b1 + a2b2 + a3b3)

In [2]:
import numpy as np

v = np.array([1,2,4])
print(v)
print(v.shape)

[1 2 4]
(3,)


In [2]:
v[1]

2

In [3]:
#one sample with three features
v = np.array([[1,2,4]])
print(v.shape)

(1, 3)


In [5]:
#three samples with one feature 
#also can call np.transpose()
v_t = v.T
print(v_t)
print(v_t.shape)

[[1]
 [2]
 [4]]
(3, 1)


In [6]:
v[0][1]

2

## Matrix
A matrix is a 2d-array of scalars with one or more columns and one or more rows. It is common to represent the features variable as a matrix with "X".

### Defining a Matrix
A matrix is represented with a 2d NumPy array constructed of a list of lists.

### Matrix Arithmetic
- **Addition**
    - Two matrices with the same dimensions can be added together
    - C = A + B
    - A + B = (a11 + b11, a12 + b12
               a21 + b21, a22 + b22
               a31 + b31, a32 + b32)

In [7]:
v = np.array([[1,2,3],[2,0,1]])
print(v)
print(v.shape)
print(v.size) #how many elements in matrix

[[1 2 3]
 [2 0 1]]
(2, 3)
6


In [8]:
v_t = v.T
print(v_t)
print(v_t.shape)
print(v_t.size)

[[1 2]
 [2 0]
 [3 1]]
(3, 2)
6


In [10]:
v = np.array([[1,2,3],[2,0,1]])
print(v.reshape(3,2))


[[1 2]
 [3 2]
 [0 1]]


In [12]:
#transform matrix into tensor
print(v.reshape(3,1,2))

[[[1 2]]

 [[3 2]]

 [[0 1]]]


In [13]:
print(v.reshape(-1,1,2))

[[[1 2]]

 [[3 2]]

 [[0 1]]]


## Tensor

In [15]:
v = np.array([[[1., 2., 3.], [4., 2., 3.]], [[7., 8., 9.], [10., 11., 12.]]])

print(v)

#first element is how many matrices, second and third shows dimensions
print(v.shape)

[[[ 1.  2.  3.]
  [ 4.  2.  3.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [16]:
print(v[0])
print(v[1])

[[1. 2. 3.]
 [4. 2. 3.]]
[[ 7.  8.  9.]
 [10. 11. 12.]]


In [17]:
print(v.size)

12


In [18]:
print(v.reshape(3,2,-1))

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 2.  3.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]


In [19]:
print(v.shape)

(2, 2, 3)


### 4D Tensor

In [21]:
v = np.zeros((2, 3, 5, 5)) # <= two rows and three columns of 5 x 5
print(v)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


### 5D Tensor

In [23]:
v = np.zeros((2, 2, 3, 5, 5))
print(v)

[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]]



 [[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 

In [25]:
print(v[0][0].shape)
print(v[0][1].shape)
print(v[1][0].shape)
print(v[1][1].shape)

(3, 5, 5)
(3, 5, 5)
(3, 5, 5)
(3, 5, 5)


### Matrix Multiplication

In [5]:
a = np.array([[2,0],[1,3]])
b = np.array([4,5])

c = np.dot(a, b)
c

array([ 8, 19])

### Elementwise Multiplication

In [7]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.multiply(a, b)
print(c)

d = np.multiply(b,a)
print(d)

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
