## Vector

In [2]:
import numpy as np

v = np.array([1,2,4])
print(v)
print(v.shape)

[1 2 4]
(3,)


In [2]:
v[1]

2

In [3]:
#one sample with three features
v = np.array([[1,2,4]])
print(v.shape)

(1, 3)


In [5]:
#three samples with one feature 
#also can call np.transpose()
v_t = v.T
print(v_t)
print(v_t.shape)

[[1]
 [2]
 [4]]
(3, 1)


In [6]:
v[0][1]

2

## Matrix

In [7]:
v = np.array([[1,2,3],[2,0,1]])
print(v)
print(v.shape)
print(v.size) #how many elements in matrix

[[1 2 3]
 [2 0 1]]
(2, 3)
6


In [8]:
v_t = v.T
print(v_t)
print(v_t.shape)
print(v_t.size)

[[1 2]
 [2 0]
 [3 1]]
(3, 2)
6


In [10]:
v = np.array([[1,2,3],[2,0,1]])
print(v.reshape(3,2))


[[1 2]
 [3 2]
 [0 1]]


In [12]:
#transform matrix into tensor
print(v.reshape(3,1,2))

[[[1 2]]

 [[3 2]]

 [[0 1]]]


In [13]:
print(v.reshape(-1,1,2))

[[[1 2]]

 [[3 2]]

 [[0 1]]]


## Tensor

In [15]:
v = np.array([[[1., 2., 3.], [4., 2., 3.]], [[7., 8., 9.], [10., 11., 12.]]])

print(v)

#first element is how many matrices, second and third shows dimensions
print(v.shape)

[[[ 1.  2.  3.]
  [ 4.  2.  3.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [16]:
print(v[0])
print(v[1])

[[1. 2. 3.]
 [4. 2. 3.]]
[[ 7.  8.  9.]
 [10. 11. 12.]]


In [17]:
print(v.size)

12


In [18]:
print(v.reshape(3,2,-1))

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 2.  3.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]


In [19]:
print(v.shape)

(2, 2, 3)


### 4D Tensor

In [21]:
v = np.zeros((2, 3, 5, 5)) # <= two rows and three columns of 5 x 5
print(v)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


### 5D Tensor

In [23]:
v = np.zeros((2, 2, 3, 5, 5))
print(v)

[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]]



 [[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 

In [25]:
print(v[0][0].shape)
print(v[0][1].shape)
print(v[1][0].shape)
print(v[1][1].shape)

(3, 5, 5)
(3, 5, 5)
(3, 5, 5)
(3, 5, 5)


### Matrix Multiplication

In [5]:
a = np.array([[2,0],[1,3]])
b = np.array([4,5])

c = np.dot(a, b)
c

array([ 8, 19])

### Elementwise Multiplication

In [7]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.multiply(a, b)
print(c)

d = np.multiply(b,a)
print(d)

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
